add_test( [==[Usual request]==] /home/user/projects/Http/test/HttpTests [==[--test-case=Usual request]==])
set_tests_properties( [==[Usual request]==] PROPERTIES WORKING_DIRECTORY /home/user/projects/Http/test LABELS)
add_test( [==[Unusual request]==] /home/user/projects/Http/test/HttpTests [==[--test-case=Unusual request]==])
set_tests_properties( [==[Unusual request]==] PROPERTIES WORKING_DIRECTORY /home/user/projects/Http/test LABELS)
add_test( [==[Generate request]==] /home/user/projects/Http/test/HttpTests [==[--test-case=Generate request]==])
set_tests_properties( [==[Generate request]==] PROPERTIES WORKING_DIRECTORY /home/user/projects/Http/test LABELS)
add_test( [==[Usual response]==] /home/user/projects/Http/test/HttpTests [==[--test-case=Usual response]==])
set_tests_properties( [==[Usual response]==] PROPERTIES WORKING_DIRECTORY /home/user/projects/Http/test LABELS)
add_test( [==[Usual request with wrapper]==] /home/user/projects/Http/test/HttpTests [==[--test-case=Usual request with wrapper]==])
set_tests_properties( [==[Usual request with wrapper]==] PROPERTIES WORKING_DIRECTORY /home/user/projects/Http/test LABELS)
add_test( [==[Usual request with wrapper]==] /home/user/projects/Http/test/HttpTests [==[--test-case=Usual request with wrapper]==])
set_tests_properties( [==[Usual request with wrapper]==] PROPERTIES WORKING_DIRECTORY /home/user/projects/Http/test LABELS)
set( HttpTests_TESTS [==[Usual request]==] [==[Unusual request]==] [==[Generate request]==] [==[Usual response]==] [==[Usual request with wrapper]==] [==[Usual request with wrapper]==])
