if(EXISTS "/home/user/projects/Http/test/HttpTests_tests-b858cb2.cmake")
  include("/home/user/projects/Http/test/HttpTests_tests-b858cb2.cmake")
else()
  add_test(HttpTests_NOT_BUILT-b858cb2 HttpTests_NOT_BUILT-b858cb2)
endif()
